package eg.com.mondia.restapi.model;
// Generated Jan 10, 2018 1:28:13 AM by Hibernate Tools 5.2.3.Final

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * LoOperator generated by hbm2java
 */
@Entity
@Table(name = "LO_OPERATOR")
public class LoOperator implements java.io.Serializable {

	private BigDecimal id;
	private String name;
	private String country;
	private Character serviceId;
	private Character packageId;
	private Set<Service> services = new HashSet<Service>(0);

	public LoOperator() {
	}

	public LoOperator(BigDecimal id, String name, String country) {
		this.id = id;
		this.name = name;
		this.country = country;
	}

	public LoOperator(BigDecimal id, String name, String country, Character serviceId, Character packageId,
			Set<Service> services) {
		this.id = id;
		this.name = name;
		this.country = country;
		this.serviceId = serviceId;
		this.packageId = packageId;
		this.services = services;
	}

	@Id

	@Column(name = "ID", unique = true, nullable = false, precision = 22, scale = 0)
	public BigDecimal getId() {
		return this.id;
	}

	public void setId(BigDecimal id) {
		this.id = id;
	}

	@Column(name = "NAME", nullable = false, length = 300)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "COUNTRY", nullable = false, length = 300)
	public String getCountry() {
		return this.country;
	}

	public void setCountry(String country) {
		this.country = country;
	}

	@Column(name = "SERVICE_ID", length = 1)
	public Character getServiceId() {
		return this.serviceId;
	}

	public void setServiceId(Character serviceId) {
		this.serviceId = serviceId;
	}

	@Column(name = "PACKAGE_ID", length = 1)
	public Character getPackageId() {
		return this.packageId;
	}

	public void setPackageId(Character packageId) {
		this.packageId = packageId;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "loOperator")
	public Set<Service> getServices() {
		return this.services;
	}

	public void setServices(Set<Service> services) {
		this.services = services;
	}

}
