package eg.com.mondia.restapi.model;
// Generated Jan 10, 2018 1:28:13 AM by Hibernate Tools 5.2.3.Final

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * Product generated by hbm2java
 */
@Entity
@Table(name = "PRODUCT")
public class Product implements java.io.Serializable {

	private BigDecimal id;
	private String name;
	private String description;
	private Double minPrice;
	private Double maxPrice;
	private Set<Service> services = new HashSet<Service>(0);

	public Product() {
	}

	public Product(BigDecimal id, String name) {
		this.id = id;
		this.name = name;
	}

	public Product(BigDecimal id, String name, String description, Double minPrice, Double maxPrice,
			Set<Service> services) {
		this.id = id;
		this.name = name;
		this.description = description;
		this.minPrice = minPrice;
		this.maxPrice = maxPrice;
		this.services = services;
	}

	@Id
	@GeneratedValue(strategy=GenerationType.AUTO, generator="product_seq")
	@SequenceGenerator(name="product_seq", sequenceName="product_seq", initialValue=3)
	@Column(name = "ID", unique = true, nullable = false, precision = 22, scale = 0)
	public BigDecimal getId() {
		return this.id;
	}

	public void setId(BigDecimal id) {
		this.id = id;
	}

	@Column(name = "NAME", nullable = false, length = 300)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "DESCRIPTION", length = 1000)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "MIN_PRICE", precision = 126, scale = 0)
	public Double getMinPrice() {
		return this.minPrice;
	}

	public void setMinPrice(Double minPrice) {
		this.minPrice = minPrice;
	}

	@Column(name = "MAX_PRICE", precision = 126, scale = 0)
	public Double getMaxPrice() {
		return this.maxPrice;
	}

	public void setMaxPrice(Double maxPrice) {
		this.maxPrice = maxPrice;
	}

	@JsonIgnore
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "product")
	public Set<Service> getServices() {
		return this.services;
	}

	public void setServices(Set<Service> services) {
		this.services = services;
	}
	
	/*@Override
	public String toString() {
		return "Product [id=" + id + ", name=" + name + ", description=" + description + ", minPrice=" + minPrice
				+ ", maxPrice=" + maxPrice + "]";
	}*/

}
