package eg.com.mondia.restapi.model;
// Generated Jan 10, 2018 1:28:13 AM by Hibernate Tools 5.2.3.Final

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Service generated by hbm2java
 */
@Entity
@Table(name = "SERVICE")
public class Service implements java.io.Serializable {

	private BigDecimal id;
	private Product product;
	private LoOperator loOperator;
	private String name;
	private String type;
	private BigDecimal operatorServiceId;
	private BigDecimal operatorPackageId;

	public Service() {
	}

	public Service(BigDecimal id, String name) {
		this.id = id;
		this.name = name;
	}

	public Service(BigDecimal id, Product product, LoOperator loOperator, String name, String type,
			BigDecimal operatorServiceId, BigDecimal operatorPackageId) {
		this.id = id;
		this.product = product;
		this.loOperator = loOperator;
		this.name = name;
		this.type = type;
		this.operatorServiceId = operatorServiceId;
		this.operatorPackageId = operatorPackageId;
	}

	@Id

	@Column(name = "ID", unique = true, nullable = false, precision = 22, scale = 0)
	public BigDecimal getId() {
		return this.id;
	}

	public void setId(BigDecimal id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PRODUCT_ID")
	public Product getProduct() {
		return this.product;
	}

	public void setProduct(Product product) {
		this.product = product;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "OPERATOR_ID")
	public LoOperator getLoOperator() {
		return this.loOperator;
	}

	public void setLoOperator(LoOperator loOperator) {
		this.loOperator = loOperator;
	}

	@Column(name = "NAME", nullable = false, length = 300)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "TYPE", length = 300)
	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	@Column(name = "OPERATOR_SERVICE_ID", precision = 22, scale = 0)
	public BigDecimal getOperatorServiceId() {
		return this.operatorServiceId;
	}

	public void setOperatorServiceId(BigDecimal operatorServiceId) {
		this.operatorServiceId = operatorServiceId;
	}

	@Column(name = "OPERATOR_PACKAGE_ID", precision = 22, scale = 0)
	public BigDecimal getOperatorPackageId() {
		return this.operatorPackageId;
	}

	public void setOperatorPackageId(BigDecimal operatorPackageId) {
		this.operatorPackageId = operatorPackageId;
	}

}
